export const boardData = [
  [
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
  ],
  [
    { isFlagged: false, isRevealed: false, isMine: true, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 2 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: false, isMine: true, isExploded: false, neighborCount: 0 },
  ],
  [
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: false, isMine: true, isExploded: false, neighborCount: 0 },
  ],
  [
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: false, isMine: true, isExploded: false, neighborCount: 0 },
  ],
  [
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 2 },
    { isFlagged: true, isRevealed: false, isMine: true, isExploded: false, neighborCount: 0 },
  ],
  [
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 2 },
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: true, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 2 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 2 },
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
  ],
  [
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 2 },
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 2 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 2 },
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
  ],
  [
    { isFlagged: false, isRevealed: true, isMine: true, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
  ],
  [
    { isFlagged: false, isRevealed: false, isMine: true, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 1 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
    { isFlagged: false, isRevealed: true, isMine: false, isExploded: false, neighborCount: 0 },
  ],
];
